name: Daily Raindrop Roundup

on:
  schedule:
    # Runs daily at 2 PM Eastern (6 PM UTC)
    - cron: '0 18 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  roundup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: curl, json
        
    - name: Run daily roundup
      env:
        RAINDROP_ACCESS_TOKEN: ${{ secrets.RAINDROP_ACCESS_TOKEN }}
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
      run: |

        # Run the script
        php daily_roundup.php
