name: Daily Raindrop Roundup

on:
  schedule:
    # Runs daily at 2 PM Eastern (6 PM UTC)
    - cron: '0 18 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  roundup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: curl, json
        
    - name: Run daily roundup
      env:
        RAINDROP_ACCESS_TOKEN: ${{ secrets.RAINDROP_ACCESS_TOKEN }}
        BLOGGER_CLIENT_ID: ${{ secrets.BLOGGER_CLIENT_ID }}
        BLOGGER_CLIENT_SECRET: ${{ secrets.BLOGGER_CLIENT_SECRET }}
        BLOGGER_REFRESH_TOKEN: ${{ secrets.BLOGGER_REFRESH_TOKEN }}
      run: |
        php daily_roundup.php
        
    - name: Email HTML file
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Daily Roundup - ${{ github.run_id }}"
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: "Your daily roundup HTML file is attached. Open it in a browser and copy the content to your blog."
        attachments: daily_roundup_*.html
        
    - name: Upload HTML file
      uses: actions/upload-artifact@v4
      with:
        name: daily-roundup-html
        path: daily_roundup_*.html
